services:
  python-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-backend
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists
    ports:
      - "8000:8000"
    networks:
      - app-net
    # The backend exposes FastAPI on port 8000
